--- ###This script disables firewalld and configures iptables instead.

- hosts: test
  connection: ssh
  remote_user: root
  gather_facts: false
  vars_files:
          - ./variables/configure-firewall.yml
  tasks:
          - name: stop firewalld
            shell: systemctl disable --now firewalld
          - name: mask firewalld
            shell: systemctl mask firewalld
          - name: flush firewall
            iptables:
                    flush: true
          - name: add lo rule to firewall
            iptables:
                    action: insert
                    chain: INPUT
                    in_interface: lo
                    jump: ACCEPT
          - name: add state rule
            iptables:
                    action: insert
                    chain: INPUT
                    ctstate: ESTABLISHED,RELATED
                    jump: ACCEPT
          - name: add trusted ips for ssh
            iptables:
                    action: insert
                    chain: INPUT
                    source: "{{ trusted_ssh_ips }}"
                    protocol: tcp
                    destination_port: "{{ ssh_port }}"
                    jump: ACCEPT
          - name: block untrusted ips for ssh
            iptables:
                    action: append
                    chain: INPUT
                    protocol: tcp
                    destination_port: "{{ ssh_port }}"
                    jump: DROP
          - name: add trusted ips for icmp
            iptables:
                    action: insert
                    chain: INPUT
                    protocol: icmp
                    icmp_type: 8
                    source: "{{ trusted_icmp_ips }}"
                    jump: ACCEPT
          - name: block untrusted ips for icmp
            iptables:
                    action: append
                    chain: INPUT
                    protocol: icmp
                    icmp_type: 8
                    jump: DROP
